#!/usr/bin/env python3
"""Build step.
  1. i18n/*.json -> strings.js  (English state names injected from states.js;
     --strict fails if es/he are missing any key)
  2. artifact.html - the whole site in one file for publishing as an Artifact.
"""
import base64, json, os, re, sys
from collections import OrderedDict

P = os.path.dirname(os.path.abspath(__file__))
os.chdir(P)
strict = "--strict" in sys.argv

# ---- 1. strings.js --------------------------------------------------------
states = json.loads(re.search(r'const STATES = (\[.*?\]);', open("states.js").read(), re.S).group(1))
locales = OrderedDict()
for code in ("en", "es", "he"):
    fn = f"i18n/{code}.json"
    locales[code] = json.load(open(fn), object_pairs_hook=OrderedDict) if os.path.exists(fn) else OrderedDict()
for s in states:
    locales["en"].setdefault("states." + s["abbr"], s["name"])
en_keys = set(locales["en"])
problems = []
for code in ("es", "he"):
    missing = sorted(en_keys - set(locales[code]))
    extra = sorted(set(locales[code]) - en_keys)
    print(f"{code}: {len(locales[code])} keys, {len(missing)} missing, {len(extra)} extra")
    if missing: problems.append((code, missing))
    for k in extra: print("   extra:", code, k)
    # placeholder parity: every {var} in English must survive translation
    for k, v in locales[code].items():
        if k in locales["en"]:
            a = set(re.findall(r"\{(\w+)\}", locales["en"][k])); b = set(re.findall(r"\{(\w+)\}", v))
            if a != b: print(f"   placeholder mismatch {code} {k}: en{sorted(a)} vs {sorted(b)}")
if problems:
    for code, missing in problems:
        print(f"   {code} missing: " + ", ".join(missing[:12]) + (" …" if len(missing) > 12 else ""))
    if strict: sys.exit("strict: translations incomplete")
open("strings.js", "w").write(
    "/* Generated by build.py from i18n/*.json — edit those, not this. */\n"
    "const STRINGS = " + json.dumps(locales, ensure_ascii=False, indent=0) + ";\n")
print("strings.js written")

# ---- 2. artifact.html -----------------------------------------------------
def datauri(fn):
    return "data:font/woff2;base64," + base64.b64encode(open(os.path.join("fonts", fn), "rb").read()).decode()

css = open("styles.css").read()
css = re.sub(r"url\('fonts/([^']+)'\)", lambda m: "url('%s')" % datauri(m.group(1)), css)
assert "prefers-color-scheme" not in css, "unexpected dark block"
css += ("\n.prose h4{font-family:var(--font-display);font-weight:400;font-size:clamp(1.2rem,3vw,1.6rem);"
        "line-height:1.1;margin:1.75rem 0 .5em;}\n"
        ".prose h5{font-family:var(--font-body);font-weight:700;font-size:1.15rem;margin:1.5rem 0 .4em;}\n"
        ".page{border-top:var(--border) solid var(--line);}\n.page:first-of-type{border-top:0;}\n")

idx = open("index.html").read()
def grab(fn, pat): return re.search(pat, open(fn).read(), re.S).group(1)
def anchors(h):
    for a, b in (('href="about.html"', 'href="#how"'), ('href="privacy.html"', 'href="#privacy"'),
                 ('href="accessibility.html"', 'href="#a11y"'), ('href="index.html"', 'href="#top"')):
        h = h.replace(a, b)
    return h
def demote(h):
    for a, b in (("h4", "h5"), ("h3", "h4"), ("h2", "h3"), ("h1", "h2")):
        h = re.sub(r'<%s(\s|>)' % a, r'<%s\1' % b, h); h = h.replace("</%s>" % a, "</%s>" % b)
    return h

main   = grab("index.html", r'<main id="main">(.*?)</main>')
defs   = re.search(r'(<svg class="svg-defs".*?</svg>)', idx, re.S).group(1)
header = anchors(re.search(r'(<header class="site-head">.*?</header>)', idx, re.S).group(1))
footer = anchors(re.search(r'(<footer class="site-foot">.*?</footer>)', idx, re.S).group(1))
sections = []
for fn, sid in (("about.html", "how"), ("privacy.html", "privacy"), ("accessibility.html", "a11y")):
    body = demote(grab(fn, r'<article class="prose wrap">(.*?)</article>'))
    sections.append(('<section class="page" id="%s" aria-labelledby="%s-h">\n<div class="prose wrap">\n%s\n</div>\n</section>'
                     % (sid, sid, body)).replace("<h2", '<h2 id="%s-h"' % sid, 1))
content = anchors(main + "\n" + "\n".join(sections))

# The runtime's internal-link check accepts "#anchor" and "*.html" only; the
# artifact rewrote page links to anchors, so strings must follow suit.
strings_js = open("strings.js").read()
for a, b in (("about.html", "#how"), ("privacy.html", "#privacy"), ("accessibility.html", "#a11y"), ("index.html", "#top")):
    strings_js = strings_js.replace("(" + a + ")", "(" + b + ")")

out = ("<title>Am I signed up to vote?</title>\n<style>\n" + css + "\n</style>\n"
       "<script>\n" + open("lang-init.js").read() + "\n</script>\n"
       '<a class="skip" href="#main" data-i18n="index.a7">Skip to the main part of this page</a>\n'
       '<span id="top"></span>\n' + defs + "\n" + header + "\n"
       '<main id="main">\n' + content + "\n</main>\n" + footer + "\n"
       "<script>\n" + open("states.js").read() + "\n" + strings_js + "\n" + open("i18n.js").read() + "\n" + open("script.js").read() + "\n</script>\n")
open("artifact.html", "w").write(out)
open("test-artifact.html", "w").write(
    '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    '<style>body{margin:0}img{max-width:100%}</style>\n' + out.split("</style>\n", 1)[0] +
    "</style>\n</head>\n<body>\n" + out.split("</style>\n", 1)[1] + "</body>\n</html>\n")
print("artifact.html      %6.1f KB" % (len(out.encode()) / 1024))
